apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-word-count
spec:
  image: flink:1.17.0-stream2-no-scala
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/my-flink-job.jar
    parallelism: 2
    upgradeMode: stateless